In [ ]:
# print the first element
import numpy as np
arr = np.array([10,20,30,40,50])
arr[0]

np.int64(10)

In [ ]:
# print the last element
arr = np.array([10,20,30,40,50])
arr[-1]

np.int64(50)

In [ ]:
# print element from 1 to 3 index
arr = np.array([10,20,30,40,50])
arr[1:4]

array([20, 30, 40])

In [ ]:
# reverse the array
arr[::-1]

array([50, 40, 30, 20, 10])

In [ ]:
# print the second row
matrix = np.array([[1,2,3],
                [4,5,6]])
matrix[0,]

array([1, 2, 3])

In [ ]:
# create matrix of 2X3 print shape
matrix = np.array([[1,2,3],
                [4,5,6]])
matrix.shape


(2, 3)

In [ ]:
# print the first column
matrix[0:,:1]


array([[1],
       [4]])

In [ ]:
# Extract elements from index 1 to 4
arr = np.array([1,2,3,4,5,6,7])
arr[1:5]

array([2, 3, 4, 5])

In [ ]:
# Extract first 3 elements
arr[:3]

array([1, 2, 3])

In [ ]:
# Extract last 3 elements
arr[-3:]

array([5, 6, 7])

In [ ]:
#  Reverse the array using slicing
arr[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [ ]:
#  Extract every 2nd element
arr[::2]

array([1, 3, 5, 7])

In [ ]:
# Extract elements in reverse order with step
arr[::-2]

array([7, 5, 3, 1])

In [ ]:
#  Extract elements starting from index 1 with step 2
arr[1::2]

array([2, 4, 6])

In [ ]:
# print first two rows and columns
arr = np.array([
[10,20,30],
[40,50,60],
[70,80,90]
])
arr[:2,:]

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
arr[:,:2]



array([[10, 20],
       [40, 50],
       [70, 80]])

In [ ]:
#  Last two rows and last two columns
arr[-2:,:]

array([[40, 50, 60],
       [70, 80, 90]])

In [ ]:
arr[:,-2:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [ ]:
# Entire second row
arr[1:2,:]

array([[40, 50, 60]])

In [ ]:
# Entire third column
arr[:, -1:]

array([[30],
       [60],
       [90]])

In [ ]:
arr[:2,1:]

array([[20, 30],
       [50, 60]])

In [ ]:
arr[::2,::2]

array([[10, 30],
       [70, 90]])

In [ ]:
# reverse rows and column
arr[::-1,::-1]

array([[90, 80, 70],
       [60, 50, 40],
       [30, 20, 10]])

In [ ]:
#  Extract last 2 elements
arr = np.array([10,20,30,40,50])
arr[-2:]

array([40, 50])

In [ ]:
# Extract all elements except last one
arr[:-1]

array([10, 20, 30, 40])

In [ ]:
# Reverse using negative slicing
arr[::-1]

array([50, 40, 30, 20, 10])

In [ ]:
# Extract values greater than 25
arr[arr>25]

array([30, 40, 50])

In [ ]:
# Replace values greater than 25 with 0

arr[arr>25] = 0
print(arr)

[10 20  0  0  0]


In [ ]:
# Broadcasting
arr = np.array([[10,20,30],
            [40,50,60]])
arr1 = np.array([1,2,3])
arr+arr1

array([[11, 22, 33],
       [41, 52, 63]])

In [ ]:
arr = np.array([[10,20,30],
            [40,50,60]])
arr1 = np.array([[1],[2]])
arr+arr1

array([[11, 21, 31],
       [42, 52, 62]])

In [ ]:
# find total sum
arr = np.array([[1,2,3],
[4,5,6]])
arr.sum()

np.int64(21)

In [ ]:
# Find column-wise sum
arr.sum(axis=0)

array([5, 7, 9])

In [ ]:
# find row wise sum
arr.sum(axis=1)

array([ 6, 15])

In [ ]:
# Mean of each row
arr.mean(axis=1)

array([2., 5.])

In [ ]:
arr.max(axis=0)

array([4, 5, 6])

In [ ]:
arr = np.array([1,2,3,4,5,6])
matrix = arr.reshape(2,3)
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr = np.array([1,2,3,4,5,6])
matrix = arr.reshape(3,2)
matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
matrix = np.array([[1,2,3],
[4,5,6]])
arr = matrix.flatten()
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)

[100   2   3]
